version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  app:
    build: ./.docker/php/.
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    links:
      - db
   

  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: root

  
  node:
    build: ./.docker/node/.
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

  